### ISSUE TITLE
Build release extensions only during the weekend

### ISSUE THREAD

**Issue by jcfr** [Slicer/DashboardScripts#7]
See https://github.com/Slicer/DashboardScripts/pull/6#commitcomment-14631475 for details

**Comment by jcfr** [comment]
Fixed in https://github.com/Slicer/DashboardScripts/commit/2e956e931d99c15b9239fa3868e7760cb5e94697

Cc: @fedorov @pieper

**Comment by fedorov** [comment]
+1
